[package]
name = "exploit"
version = "1.0.0"
authors = []

[addresses]
ctfmovement="0x97b79ccefaef035d35090a78241224f2a8bc7ff2f579dcd705558d43b3f56984"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.simple-swap]
local = "../3-SimpleSwap-challenge"

[dev-dependencies]
