[package]
name = "exploit"
version = "1.0.0"
authors = []

[addresses]
ctfmovement = "0x41f60a4f3eaa6d52ca6a45c38f5294e1e154540dfc689f2dca9ea11a0333fe0b"

[dev-addresses]

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.hello_move]
local = "../2-HelloMove-challenge"


